services:
  inner-circle-items-api-e2e-against-prod-tests:
    container_name: 'inner-circle-items-api-e2e-against-prod-tests'
    build:
      dockerfile: ./KarateDockerfile
      context: ./e2e
    command: [ "karate", "/karate" ]
    environment:
      AUTH_FIRST_TENANT_LOGIN_WITH_ALL_PERMISSIONS: ${AUTH_FIRST_TENANT_LOGIN_WITH_ALL_PERMISSIONS}
      AUTH_FIRST_TENANT_PASSWORD_WITH_ALL_PERMISSIONS: ${AUTH_FIRST_TENANT_PASSWORD_WITH_ALL_PERMISSIONS}
      AUTH_SECOND_TENANT_LOGIN_WITH_ALL_PERMISSIONS: ${AUTH_SECOND_TENANT_LOGIN_WITH_ALL_PERMISSIONS}
      AUTH_SECOND_TENANT_PASSWORD_WITH_ALL_PERMISSIONS: ${AUTH_SECOND_TENANT_PASSWORD_WITH_ALL_PERMISSIONS}
      AUTH_LOGIN_WITHOUT_PERMISSIONS: ${AUTH_LOGIN_WITHOUT_PERMISSIONS}
      AUTH_PASSWORD_WITHOUT_PERMISSIONS: ${AUTH_PASSWORD_WITHOUT_PERMISSIONS}
      AUTH_API_ROOT_URL: ${AUTH_API_ROOT_URL}
      API_ROOT_URL: ${API_ROOT_URL}
      SHOULD_USE_FAKE_EXTERNAL_DEPENDENCIES: "false"
