name: Publish js-client npm Package

on:
  push:
    branches: 
      - feature/generate_npm_package_with_types_and_client

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write  # Required for OIDC (https://docs.npmjs.com/trusted-publishers#github-actions-configuration)
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Run the api via docker-compose
        run: |
          docker compose --profile MockForTests up -d

      - name: Re-generate js-client by OpenAPI
        run: |
          docker compose -f ./api-types/docker-compose.yml up

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.12.0
          # Setup .npmrc file to publish to npm
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@tourmalinecore'

      - name: Add SEMVER_VERSION Env Var with Value from __version File
        run: |
          echo "SEMVER_VERSION=$(cat __version)" >>${GITHUB_ENV}

      - name: Add new Env Var with new npm package version using commit sha or __version
        run: |
          # commit to master uses __version
          should_use_sem_ver_version="${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}"
          sem_ver_version="${{ env.SEMVER_VERSION }}"
          commit_sha="${{ github.sha }}"
          commit_sha_version="${{ env.SEMVER_VERSION }}-${{ github.sha }}"
          [[ "$should_use_sem_ver_version" == "true" ]] && echo "NEW_JS_CLIENT_VERSION=${sem_ver_version}" >> ${GITHUB_ENV} || echo "NEW_JS_CLIENT_VERSION=${commit_sha_version}" >> ${GITHUB_ENV}
          [[ "$should_use_sem_ver_version" == "true" ]] && echo "NEW_JS_CLIENT_TAG=${sem_ver_version}" >> ${GITHUB_ENV} || echo "NEW_JS_CLIENT_TAG=${commit_sha}" >> ${GITHUB_ENV}

      # - name: Publish js-client npm package
      #   run: |
      #     cd js-client
      #     npm version "${{ env.NEW_JS_CLIENT_VERSION }}" --no-git-tag-version
      #     npm ci
      #     npm run build
      #     npm publish --tag "${{ env.NEW_JS_CLIENT_TAG }}" --access public
      
      - name: Commit js-client
        run: |
          git config user.email "contact@tourmalinecore.com"
          git config user.name "Workflow Action"
          
          git commit js-client/index.ts -m "chore(js-client): Update js-client by OpenAPI [skip ci]" || echo "No changes to commit"
          
          git status

          # these fetch and rebase were needed to address an issue when there are 2 or more parallel jobs which commit
          # these jobs are doing it concurrently and there were a race condition, only the first modifier could push its changes
          git fetch origin ${{ github.head_ref || github.ref_name }}
          git rebase origin/${{ github.head_ref || github.ref_name }}
          git push origin HEAD:${{ github.head_ref || github.ref_name }} || echo "No changes to commit"
