name: Release New Version (If Needed)

on:
  push:
    branches:
      - feature/fix_deployment_from_master_on_version_change

jobs:
  release-new-version:
    runs-on: ubuntu-24.04
    # permissions:
    #   contents: write # to be able to publish a GitHub release
    #   issues: write # to be able to comment on released issues
    #   pull-requests: write # to be able to comment on released pull requests
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          # Downloads the entire commit history for semantic-release
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.12.0

      - name: Install semantic-release and plugins
        run: |
          npm install semantic-release@25.0.2 \
            @semantic-release/exec@7.1.0 \
            @semantic-release/commit-analyzer@13.0.1 \
            @semantic-release/release-notes-generator@14.1.0 \
            @semantic-release/github@12.0.2 \
            @semantic-release/git@10.0.1 \
            conventional-changelog-conventionalcommits@9.1.0

      - name: Configure Git
        run: |
          git config user.email "contact@tourmalinecore.com"
          git config user.name "Workflow Action"

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.INNER_CIRCLE_SEMANTIC_RELEASE_GH_TOKEN }}
        run: npx semantic-release
