name: Release New Version (If Needed)

on:
  push:
    branches:
      - feature/add-semantic-release

jobs:
  release-new-version:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          # Downloads the entire commit history for semantic-release
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.12.0

      - name: Install semantic-release and plugins
        run: |
          npm install semantic-release \
            @semantic-release/exec \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/github \
            @semantic-release/git

      - name: Configure Git
        run: |
          git config user.email "contact@tourmalinecore.com"
          git config user.name "Workflow Action"

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
